export const disciplinas = [
  { id: 1, label: "Processamento de Linguagem Natural", subtitle: "PRG0018" },
  { id: 2, label: "Estrutura de Dados", subtitle: "SCC0122" },
  {
    id: 3,
    label: "Introdução à Ciência de Computação II",
    subtitle: "SCC0201",
  },
  { id: 4, label: "Algoritmos e Estruturas de Dados I", subtitle: "SCC0202" },
  {
    id: 5,
    label: "Teoria da Computação e Linguagens Formais",
    subtitle: "SCC0205",
  },
  { id: 6, label: "Computadores e Sociedade I", subtitle: "SCC0207" },
  { id: 7, label: "Empreendedores em Informática", subtitle: "SCC0209" },
  {
    id: 8,
    label: "Laboratório de Algoritmos Avançados II",
    subtitle: "SCC0211",
  },
  {
    id: 9,
    label: "Metodologia de Pesquisa em Computação",
    subtitle: "SCC0213",
  },
  { id: 10, label: "Algoritmos Avançados e Aplicações", subtitle: "SCC0218" },
  { id: 11, label: "Introdução ao Desenvolvimento Web", subtitle: "SCC0219" },
  {
    id: 12,
    label: "Laboratório de Introdução à Ciência de Computação II",
    subtitle: "SCC0220",
  },
  { id: 13, label: "Estruturas de dados I", subtitle: "SCC0223" },
  {
    id: 14,
    label: "Seminários de Computação I (quinzenal)",
    subtitle: "SCC0227",
  },
  {
    id: 15,
    label: "Seminários de Computação III (quinzenal)",
    subtitle: "SCC0229",
  },
  { id: 16, label: "Inteligência Artificial", subtitle: "SCC0230" },
  {
    id: 17,
    label: "Aplicações de Aprendizado de Máquina e Mineração de Dados",
    subtitle: "SCC0233",
  },
  { id: 18, label: "Laboratório de Bases de Dados", subtitle: "SCC0241" },
  {
    id: 19,
    label: "Mineração a partir de Grandes Bases de Dados",
    subtitle: "SCC0244",
  },
  { id: 20, label: "Computação Gráfica", subtitle: "SCC0250" },
  { id: 21, label: "Visualização Computacional", subtitle: "SCC0252" },
  {
    id: 22,
    label: "Interação Humano-Computador e Experiência do Usuário",
    subtitle: "SCC0260",
  },
  { id: 23, label: "Introdução à Bioinformática", subtitle: "SCC0271" },
  { id: 24, label: "Robôs Móveis e Inteligentes", subtitle: "SCC0273" },
  { id: 25, label: "Introdução à Ciência de Dados", subtitle: "SCC0275" },
  { id: 26, label: "Competições de Ciência de Dados", subtitle: "SCC0277" },
  { id: 27, label: "Introdução à Web Semântica", subtitle: "SCC0283" },
  { id: 28, label: "Sistemas de Recomendação", subtitle: "SCC0284" },
  { id: 29, label: "Mineração de Dados Não Estruturados", subtitle: "SCC0287" },
  { id: 30, label: "Projeto de Intercâmbio I", subtitle: "SCC0289" },
  { id: 31, label: "Projeto de Intercâmbio II", subtitle: "SCC0290" },
  { id: 32, label: "Estágio Supervisionado I", subtitle: "SCC0291" },
  { id: 33, label: "Estágio Supervisionado II", subtitle: "SCC0292" },
  { id: 34, label: "Projeto de Graduação I", subtitle: "SCC0293" },
  { id: 35, label: "Projeto de Graduação II", subtitle: "SCC0294" },
  { id: 36, label: "Projeto Empreendedor I", subtitle: "SCC0300" },
  { id: 37, label: "Projeto Empreendedor II", subtitle: "SCC0302" },
  { id: 38, label: "Algoritmos e Estruturas de Dados I", subtitle: "SCC0502" },
  { id: 39, label: "Bases de Dados", subtitle: "SCC0540" },
  {
    id: 40,
    label: "Interação Humano-Computador e Experiência do Usuário",
    subtitle: "SCC0560",
  },
  {
    id: 41,
    label: "Acessibilidade em Sistemas Computacionais",
    subtitle: "SCC0580",
  },
  { id: 42, label: "Programação Orientada a Objetos", subtitle: "SCC0604" },
  { id: 43, label: "Estruturas de Dados III", subtitle: "SCC0607" },
  { id: 44, label: "Bases de Dados", subtitle: "SCC0640" },
  { id: 45, label: "Laboratório de Bases de Dados", subtitle: "SCC0641" },
  { id: 46, label: "Computação Gráfica", subtitle: "SCC0650" },
  {
    id: 47,
    label:
      "Tópicos Avançados em Ciências de Computação I - Aprendizado de Máquina para Séries Temporais",
    subtitle: "SCC0910",
  },
  {
    id: 48,
    label:
      "Tópicos Avançados em Ciências de Computação I - Redes Complexas para Ciências da Computação",
    subtitle: "SCC0910",
  },
  {
    id: 49,
    label:
      "Tópicos Avançados em Ciências de Computação II - Computação Bioinspirada",
    subtitle: "SCC0911",
  },
];

export const docentes = [
  { id: 1, label: "Thiago Alexandre S. Pardo" },
  { id: 2, label: "André de Freitas Smaira" },
  { id: 3, label: "Diego Raphael Amancio" },
  { id: 4, label: "Marcelo Garcia Manzato" },
  { id: 5, label: "Rudinei Goularte" },
  { id: 6, label: "Joao Luis Garcia Rosa" },
  { id: 7, label: "Renato Moraes Silva" },
  { id: 8, label: "Bruna Carolina R. da Cunha" },
  { id: 9, label: "Solange Oliveira Rezende" },
  { id: 10, label: "João do Espírito Santo B. Neto" },
  { id: 11, label: "Agma Juci Machado Traina" },
  { id: 12, label: "Maria Cristina F. Oliveira" },
  { id: 13, label: "Alneu de Andrade Lopes" },
  { id: 14, label: "Diego Furtado Silva" },
  { id: 15, label: "José Fernando Rodrigues Junior" },
  { id: 16, label: "Caetano Traina Jr" },
  { id: 17, label: "Jean Roberto Ponciano" },
  { id: 18, label: "Kamila Rios da Hora Rodrigues" },
  { id: 19, label: "Ricardo Cerri" },
  { id: 20, label: "Roseli Ap. Francelin Romero" },
  { id: 21, label: "Ricardo Marcondes Marcacini" },
  { id: 22, label: "Moacir Antonelli Ponti" },
  { id: 23, label: "Elaine Parros Machado de Sousa" },
  { id: 24, label: "Dilvan de Abreu Moreira" },
];

export const semestre = [
  { id: 1, label: "2024.1" },
  { id: 2, label: "2024.2" },
  { id: 3, label: "2025.1" },
];

export const avaliacoes = [
  {
    evaluationId: 1,
    teacherName: "Thiago Alexandre S. Pardo",
    courseName: "Processamento de Linguagem Natural",
    courseCode: "PRG0018",
    status: "Pendente",
    semester: "2024.1",
  },
  {
    evaluationId: 2,
    teacherName: "André de Freitas Smaira",
    courseName: " Estrutura de Dados",
    courseCode: " SCC0122",
    status: "Aprovado",
    semester: "2024.2",
  },
  {
    evaluationId: 3,
    teacherName: "Diego Raphael Amancio",
    courseName: "Introdução à Ciência de Computação II",
    courseCode: "SCC0201",
    status: "Reprovado",
    semester: "2025.1",
  },
  {
    evaluationId: 4,
    teacherName: "Marcelo Garcia Manzato",
    courseName: "Algoritmos e Estruturas de Dados I",
    courseCode: " SCC0202",
    status: "Em revisão",
    semester: "2025.1",
  },
  {
    evaluationId: 5,
    teacherName: "Thiago Alexandre S. Pardo",
    courseName: "Processamento de Linguagem Natural",
    courseCode: "PRG0018",
    status: "Pendente",
    semester: "2024.1",
  },
  {
    evaluationId: 6,
    teacherName: "André de Freitas Smaira",
    courseName: " Estrutura de Dados",
    courseCode: " SCC0122",
    status: "Aprovado",
    semester: "2024.2",
  },
  {
    evaluationId: 7,
    teacherName: "Diego Raphael Amancio",
    courseName: "Introdução à Ciência de Computação II",
    courseCode: "SCC0201",
    status: "Reprovado",
    semester: "2025.1",
  },
  {
    evaluationId: 8,
    teacherName: "Marcelo Garcia Manzato",
    courseName: "Algoritmos e Estruturas de Dados I",
    courseCode: " SCC0202",
    status: "Em revisão",
    semester: "2025.1",
  },
  {
    evaluationId: 9,
    teacherName: "Thiago Alexandre S. Pardo",
    courseName: "Processamento de Linguagem Natural",
    courseCode: "PRG0018",
    status: "Pendente",
    semester: "2024.1",
  },
  {
    evaluationId: 10,
    teacherName: "André de Freitas Smaira",
    courseName: " Estrutura de Dados",
    courseCode: " SCC0122",
    status: "Aprovado",
    semester: "2024.2",
  },
  {
    evaluationId: 11,
    teacherName: "Diego Raphael Amancio",
    courseName: "Introdução à Ciência de Computação II",
    courseCode: "SCC0201",
    status: "Reprovado",
    semester: "2025.1",
  },
  {
    evaluationId: 12,
    teacherName: "Marcelo Garcia Manzato",
    courseName: "Algoritmos e Estruturas de Dados I",
    courseCode: " SCC0202",
    status: "Em revisão",
    semester: "2025.1",
  },
  {
    evaluationId: 13,
    teacherName: "Thiago Alexandre S. Pardo",
    courseName: "Processamento de Linguagem Natural",
    courseCode: "PRG0018",
    status: "Pendente",
    semester: "2024.1",
  },
  {
    evaluationId: 14,
    teacherName: "André de Freitas Smaira",
    courseName: " Estrutura de Dados",
    courseCode: " SCC0122",
    status: "Aprovado",
    semester: "2024.2",
  },
  {
    evaluationId: 15,
    teacherName: "Diego Raphael Amancio",
    courseName: "Introdução à Ciência de Computação II",
    courseCode: "SCC0201",
    status: "Reprovado",
    semester: "2025.1",
  },
  {
    evaluationId: 16,
    teacherName: "Marcelo Garcia Manzato",
    courseName: "Algoritmos e Estruturas de Dados I",
    courseCode: " SCC0202",
    status: "Em revisão",
    semester: "2025.1",
  },
  {
    evaluationId: 17,
    teacherName: "Thiago Alexandre S. Pardo",
    courseName: "Processamento de Linguagem Natural",
    courseCode: "PRG0018",
    status: "Pendente",
    semester: "2024.1",
  },
  {
    evaluationId: 18,
    teacherName: "André de Freitas Smaira",
    courseName: " Estrutura de Dados",
    courseCode: " SCC0122",
    status: "Aprovado",
    semester: "2024.2",
  },
  {
    evaluationId: 19,
    teacherName: "Diego Raphael Amancio",
    courseName: "Introdução à Ciência de Computação II",
    courseCode: "SCC0201",
    status: "Reprovado",
    semester: "2025.1",
  },
  {
    evaluationId: 20,
    teacherName: "Marcelo Garcia Manzato",
    courseName: "Algoritmos e Estruturas de Dados I",
    courseCode: " SCC0202",
    status: "Em revisão",
    semester: "2025.1",
  },
  {
    evaluationId: 21,
    teacherName: "Thiago Alexandre S. Pardo",
    courseName: "Processamento de Linguagem Natural",
    courseCode: "PRG0018",
    status: "Pendente",
    semester: "2024.1",
  },
  {
    evaluationId: 22,
    teacherName: "André de Freitas Smaira",
    courseName: " Estrutura de Dados",
    courseCode: " SCC0122",
    status: "Aprovado",
    semester: "2024.2",
  },
  {
    evaluationId: 23,
    teacherName: "Diego Raphael Amancio",
    courseName: "Introdução à Ciência de Computação II",
    courseCode: "SCC0201",
    status: "Reprovado",
    semester: "2025.1",
  },
  {
    evaluationId: 24,
    teacherName: "Marcelo Garcia Manzato",
    courseName: "Algoritmos e Estruturas de Dados I",
    courseCode: " SCC0202",
    status: "Em revisão",
    semester: "2025.1",
  },
];

export const questions = [
  {
    questionId: 1,
    questionText: "Como você avalia a clareza das explicações do professor?",
    questionType: "rating",
    order: 1,
  },
  {
    questionId: 2,
    questionText: "O professor está disponível para tirar dúvidas?",
    questionType: "yesno",
    order: 2,
  },
  {
    questionId: 3,
    questionText: "Quais aspectos positivos você destacaria na aula?",
    questionType: "text",
    order: 3,
  },
  {
    questionId: 4,
    questionText:
      "Quais aspectos negativos você destacaria na aula e que poderiam ser melhorados?",
    questionType: "text",
    order: 4,
  },
];

export const answer1 = {
  evaluationId: 1,
  userName: "Pedrão da silva",
  userEmail: "pedraodasilva@gmail.com",
  userNusp: "123456789",
  status: "Pendente",
  approvedBy: null,
  answers: [
    {
      questionId: 1,
      questionType: "text",
      question: "Como você avalia a clareza das explicações do professor?",
      order: 1,
      answer: "As explicações do professor foram muito claras e objetivas.",
      editedAnswer:
        "As explicações do professor foram muito claras e objetivas.",
      editedBy: "Ademiro",
    },
    {
      questionId: 2,
      questionType: "yesno",
      question: "O professor está disponível para tirar dúvidas?",
      order: 2,
      answer: "Sim",
      editedAnswer: "Sim",
      editedBy: "Ademiro",
    },
    {
      questionId: 3,
      questionType: "text",
      question: "Quais aspectos positivos você destacaria na aula?",
      order: 3,
      answer: "A aula foi muito interessante e o professor é muito bom.",
      editedAnswer: "A aula foi muito interessante e o professor é muito bom.",
      editedBy: null,
    },
    {
      questionId: 4,
      questionType: "text",
      question:
        "Quais aspectos negativos você destacaria na aula e que poderiam ser melhorados?",
      order: 4,
      answer: "",
      editedAnswer: "",
      editedBy: null,
    },
  ],
};

export const answer2 = {
  evaluationId: 2,
  userName: "Matheus poncicicicio",
  userEmail: "poncianoceara@gmail.com",
  userNusp: "987654321",
  status: "Aprovado",
  approvedBy: "pedrão ademiro",
  answers: [
    {
      questionId: 1,
      questionType: "text",
      question: "Como você avalia a clareza das explicações do professor?",
      order: 1,
      answer: "As explicações do professor foram HORRIVEIS.",
      editedAnswer:
        "As explicações do professor foram ruins.",
      editedBy: "Ademiro",
    },
    {
      questionId: 2,
      questionType: "yesno",
      question: "O professor está disponível para tirar dúvidas?",
      order: 2,
      answer: "NAOPOOOOOOO",
      editedAnswer: "nao",
      editedBy: "Ademiro",
    },
    {
      questionId: 3,
      questionType: "text",
      question: "Quais aspectos positivos você destacaria na aula?",
      order: 3,
      answer: "A aula foi muito interessante e o professor é feio horroso.",
      editedAnswer: "A aula foi muito interessante e o professor é desprovido de inteligência.",
      editedBy: null,
    },
    {
      questionId: 4,
      questionType: "text",
      question:
        "Quais aspectos negativos você destacaria na aula e que poderiam ser melhorados?",
      order: 4,
      answer: "didática, explicação, carisma, inteligencia, beleza, simpatia, compreensão, etc.",
      editedAnswer: "",
      editedBy: null,
    },
  ],
};

export const teacher_courses = [
  {
    teacherId: 1,
    teacherName: "Thiago Alexandre S. Pardo",
    courseId: 1,
    courseName: "Processamento de Linguagem Natural",
    courseCode: "PRG0018",
  },
  {
    teacherId: 2,
    teacherName: "André de Freitas Smaira",
    courseId: 11,
    courseName: "Introdução ao Desenvolvimento Web",
    courseCode: "SCC0219",
  },
  {
    teacherId: 3,
    teacherName: "Diego Raphael Amancio",
    courseId: 16,
    courseName: "Inteligência Artificial",
    courseCode: "SCC0230",
  },
  {
    teacherId: 4,
    teacherName: "Marcelo Garcia Manzato",
    courseId: 17,
    courseName: "Aplicações de Aprendizado de Máquina e Mineração de Dados",
    courseCode: "SCC0233",
  },
  {
    teacherId: 5,
    teacherName: "Rudinei Goularte",
    courseId: 39,
    courseName: "Bases de Dados",
    courseCode: "SCC0540",
  },
  {
    teacherId: 6,
    teacherName: "Joao Luis Garcia Rosa",
    courseId: 24,
    courseName: "Robôs Móveis e Inteligentes",
    courseCode: "SCC0273",
  },
  {
    teacherId: 9,
    teacherName: "Solange Oliveira Rezende",
    courseId: 25,
    courseName: "Introdução à Ciência de Dados",
    courseCode: "SCC0275",
  },
  {
    teacherId: 13,
    teacherName: "Alneu de Andrade Lopes",
    courseId: 28,
    courseName: "Sistemas de Recomendação",
    courseCode: "SCC0284",
  },
  {
    teacherId: 14,
    teacherName: "Diego Furtado Silva",
    courseId: 27,
    courseName: "Introdução à Web Semântica",
    courseCode: "SCC0283",
  },
  {
    teacherId: 22,
    teacherName: "Moacir Antonelli Ponti",
    courseId: 47,
    courseName:
      "Tópicos Avançados em Ciências de Computação I - Aprendizado de Máquina para Séries Temporais",
    courseCode: "SCC0910",
  },
];

export const status = [
  { id: 1, label: "Pendente" },
  { id: 2, label: "Aprovado" },
  { id: 3, label: "Reprovado" },
  { id: 4, label: "Em revisão" },
]

export const semester  = [
  { id: 1, value: "2024.1" },
  { id: 2, value: "2024.2" },
  { id: 3, value: "2025.1" },
]

